### ISSUE TITLE
Hide bar bubbles in battlegrounds

### ISSUE THREAD

**Issue by stygz** [spiralofhope/TidyBar#34] opened 2016-08-13 13:17 UTC
There is an issue with the honor/exp bar in Battleground games.
![bg](https://cloud.githubusercontent.com/assets/20715603/17643377/3022e416-619b-11e6-8e60-cc787d89ce9b.png)
This is with the latest version.

**Comment by spiralofhope** [comment] 2016-08-13 19:47
I don't do battlegrounds, but I'm familiar with those bubbles and I'll take a look.

**Comment by stygz** [comment] 2016-08-14 02:39
thank you

**Comment by spiralofhope** [comment] 2016-08-16 22:57
Because I don't ever PvP, it's hard for me to test this.

What exactly are you doing just before you see the bubbles?

----

Copy/paste one of these lines, and tell me if they (temporarily) fix this problem:

``` lua
/run for i=1,19 do _G[ 'MainMenuXPBarDiv' .. i ]:SetAlpha( 0 ) end
```

``` lua
/run for i=1,19 do _G[ 'MainMenuXPBarDiv' .. i ]:Hide() end
```

Or this line, changing that number:

``` lua
/run ReputationWatchBar.StatusBar.XPBarTexture0:SetAlpha( 0 )
/run ReputationWatchBar.StatusBar.XPBarTexture1:SetAlpha( 0 )
/run ReputationWatchBar.StatusBar.XPBarTexture2:SetAlpha( 0 )
/run ReputationWatchBar.StatusBar.XPBarTexture3:SetAlpha( 0 )
```

**Comment by spiralofhope** [comment] 2016-08-16 23:54
-- possible battlegrounds fixes for issue 34
  --events.UPDATE_WORLD_STATES          = TidyBar_RefreshPositions --  Fired within Battlefields when certain things occur such as a flag being captured. Also seen in the outdoor world occasionlly, but it's not clear what triggers it.
  --events.WORLD_MAP_UPDATE                   = TidyBar_RefreshPositions  --  Fired when the world map should be updated.  When entering a battleground, this event won't fire until the zone is changed (i.e. in WSG when you walk outside of Warsong Lumber Mill or Silverwing Hold --Salanex

**Comment by stygz** [comment] 2016-08-23 00:53
Tried using this lines but none of it seem to work.

**Comment by stygz** [comment] 2016-08-23 02:19
I think that bubble belong to the new exp bar for the honor system

**Comment by stygz** [comment] 2016-08-29 13:32
hi any update on this issue? thanks

**Comment by spiralofhope** [comment] 2016-08-30 10:54
I cannot reproduce that issue.  I need you to /fstack and hover over them and get me some more information.

**Comment by stygz** [comment] 2016-08-31 01:04
I did a fstack and its actually the artifact bar.

**Comment by spiralofhope** [comment] 2016-08-31 13:45
7.0.3.18 is up, with additional corrections.

Supporting the artifact bar has broken things in other ways though (see the issues list).

**Comment by spiralofhope** [comment] 2016-09-01 12:25
7.0.3.19 is up, and I'm happy with this bar's fixes.

#40 is outstanding, but that shouldn't matter to you.

I'm assuming this bug is also fixed.  Closing this ticket.

**Closed by spiralofhope** 2016-09-01 12:25 UTC
